### PR TITLE
Remove RHUI repos for 8.6 and 9.0 GA

### PR DESCRIPTION
**Pull request by atodorov**
these repos are causing the Composer Test failures in https://github.com/osbuild/osbuild/pull/1051

### CODE REVIEW

**Review by jrusz — COMMENTED** [review]
Those repos are not causing test failures, just failures in the `ci_details.sh` script. The test failures are caused by I suppose old qcow2 test case. The fix is to regenerate them, I don't think this is necessary.

**Comment by atodorov** [comment]
> Curl error (58): Problem with the local SSL certificate for https://rhui.us-east-1.aws.ce.redhat.com/pulp/mirror/content/dist/rhel8/rhui/8/x86_64/appstream/os [could not load PEM client certificate

That's a clear error message for the RHUI repository. If this repo is failing we don't want it anyway regardless if that's related to other issues or not.

**Comment by atodorov** [comment]
Another failure caused by this -> https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/2652231130

So not related to #1051 but definitely looks like its causing troubles.

**Review by jrusz — APPROVED** [review]
Yeah ok let's remove them

**Pull request merged**
