### PR TITLE
COMPOSER-1576: Add definitions for RHEL 8.6 GA images

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Review by jrusz — COMMENTED** [review]
Are you sure about the `ec2-user`? I thought we have `cloud-user` in RHEL, otherwise looks good, but don't you want to add the RHEL-8.6 GA image definition for `rhos-01` Openstack as well? I guess they could be under the same commit....

And idk about the removal of `openstack` we do not use it true, but we don't need to remove it either, right? I'm fine with removing it if @ondrejbudai sees no issue with that...

**Comment by atodorov** [comment]
> Are you sure about the ec2-user?

That's what we've got in the 8.5 GA definitions. I just copied them and changed the names & AMI ID value.

**Review by jrusz — CHANGES_REQUESTED** [review]
> > Are you sure about the ec2-user?
> 
> That's what we've got in the 8.5 GA definitions. I just copied them and changed the names & AMI ID value.

Ok you're right it works with `ec2-user`. I guess in case any problems arise we can bring back the openstack definitions so I'm fine with that.

So my only remaining question is what about the RHOS-01 Openstack definition? Any reason why not include it with this change?

**Comment by atodorov** [comment]
> So my only remaining question is what about the RHOS-01 Openstack definition? Any reason why not include it with this change?

I wasn't there yet, but will include the definitions either here or in a separate PR. Following up on them step by step.

**Review by jrusz — DISMISSED** [review]
> I wasn't there yet, but will include the definitions either here or in a separate PR. Following up on them step by step.

Ok I'll leave that up to you when to add them then, LGTM otherwise.

**Comment by atodorov** [comment]
RHOS image ids confirmed by EXD.

**Review by jrusz — DISMISSED** [review]
All the image ids look good as well as configs, I didn't try provisioning all of these machines in Gitlab CI yet, but LGTM. 

I just don't know about the aws metal instances, we didn't have one for GA, so I guess that's the reason why you didn't add one for 8.6 and 9.0 GA either but maybe we could use it sometime? Idk afaik we didn't use the metal instances yet....

**Comment by ondrejbudai** [comment]
I would prefer to be more slow, firstly introduce the new machines, do the switch and then remove the old ones. If we remove them firstly and need to change something else while the change isn't propagated everywhere yet, this will get painful.

About metal: Let's not care about them, I will probably delete them later.

**Comment by ondrejbudai** [comment]
#63 introduced merge conflicts, so I rebased this PR. All image IDs are the same, just some image types might have changed.

**Comment by jrusz** [comment]
Ugh yeah well those 8.7 and 9.1 images no longer exist in RHOS-01... I'll just take some nightly qcows and upload them for our use.

**Pull request merged**
