### PR TITLE
Workaround flaky internal DNS

### PR DESCRIPTION
**Pull request by thozza**
The DNS resolvers provided by DHCP in AWS are flaky when being queried for the VSphere instance IP address. This makes the VSphere tests in osbuild-composer fail a lot on not being able to resolve the hostname.

Add the IP address and hostname to /etc/hosts as a temporary workaround, until IT fixes the issue.

### CODE REVIEW

**Comment by thozza** [comment]
Being tested in https://github.com/osbuild/osbuild-composer/pull/3298

**Comment by jrusz** [comment]
I believe you need to create a branch here in the upstream repo, it won't work with commit SHA from your fork...

**Comment by thozza** [comment]
> I believe you need to create a branch here in the upstream repo, it won't work with commit SHA from your fork...

I think you are right 😭

**Comment by thozza** [comment]
created https://github.com/osbuild/gitlab-ci-terraform/pull/89

**Pull request closed without merging**
